'use client'
import { useState } from 'react'
import Link from 'next/link'
import { ERDisclaimerBanner, ERDisclaimerFooter, ERResultCaution } from '@/components/tools/ERDisclaimer'
interface Choice{label:string;value:string;icon?:string;danger?:boolean}
interface TreeNode{id:string;title:string;desc?:string;choices?:Choice[];result?:{severity:'critical'|'urgent'|'moderate'|'low';title:string;actions:string[];workup:string[];disposition:string;pitfall?:string};next?:(s:string)=>string}
const tree:Record<string,TreeNode>={
  start:{id:'start',title:'Step 1: 院内発熱の初期評価',desc:'入院48h以降の新規発熱。5Dで鑑別: Drug（薬剤熱）, Device（カテーテル感染）, DVT/PE, Decubitus, C. difficile。術後発熱はW³I²F（術後日数別）。',
    choices:[
      {label:'好中球減少性発熱（FN: 好中球<500/μL + 体温≧38℃）',value:'fn',icon:'🚨',danger:true},
      {label:'術後発熱',value:'postop',icon:'🔪'},
      {label:'中心静脈カテーテル留置中',value:'cvc',icon:'💉',danger:true},
      {label:'尿道カテーテル留置中',value:'cauti',icon:'🚿'},
      {label:'抗菌薬使用中 + 下痢あり（CDI疑い）',value:'cdi',icon:'💊'},
      {label:'上記に該当しない院内発熱',value:'general',icon:'🔍'},
    ],next:v=>v,
  },
  fn:{id:'fn',title:'🚨 好中球減少性発熱（FN）',
    result:{severity:'critical',title:'FN — 30分以内に抗菌薬',
      actions:['血液培養2セット（末梢 + CVC両方から）採取 → 即座に広域抗菌薬開始','経験的抗菌薬: CFPM or MEPM or TAZ/PIPC（施設プロトコル参照）','MASCCスコアで低リスク(<21)/高リスク(≧21)を評価','低リスク: 経口LVFX + AMPC/CVA（外来管理の検討も）','高リスク: iv抗菌薬 + 入院管理','48-72hで再評価: 培養結果に基づくde-escalation or 抗真菌薬追加','G-CSF投与の検討（感染症科/血液内科と相談）','真菌感染: 4-7日で改善なし → βDグルカン + ガラクトマンナン → 抗真菌薬（MCFG or L-AMB）'],
      workup:['血液培養2セット（CVC + 末梢）','CBC（ANC確認）','CRP・PCT','電解質・腎機能・肝機能','胸部X線','尿検査・尿培養','βDグルカン（真菌感染疑い時）','CT（感染巣不明時）'],
      disposition:'入院（高リスク）。低リスクMASCC→外来管理可の場合あり',
      pitfall:'FNは30分が命。「培養結果を待って」は禁忌。好中球減少時は炎症反応が乏しい（CRP上がらない・膿が形成されない）ため、身体所見が軽微でも重症感染の可能性',
    },
  },
  postop:{id:'postop',title:'Step 2: 術後発熱 — W³I²F',
    desc:'術後発熱の時期別鑑別: Wind(肺炎/無気肺 1-2日), Water(UTI 3-5日), Wound(創部感染 5-7日), Walking(DVT 5+日), Wonder drugs(薬剤熱 任意)。',
    choices:[
      {label:'術後1-2日（Wind: 無気肺/肺炎）',value:'postop_wind',icon:'🫁'},
      {label:'術後3-5日（Water: UTI / Wound: 創部）',value:'postop_water_wound',icon:'💧'},
      {label:'術後5日以降（Walking: DVT/PE）',value:'postop_dvt',icon:'🦵'},
      {label:'術後いつでも（Wonder drugs: 薬剤熱）',value:'drug_fever',icon:'💊'},
    ],next:v=>v,
  },
  postop_wind:{id:'postop_wind',title:'術後1-2日: 無気肺/肺炎',
    result:{severity:'moderate',title:'術後早期発熱 — 無気肺が最多',
      actions:['無気肺: 最も頻度が高い。incentive spirometry + 早期離床 + 深呼吸促進','肺炎: 膿性痰 + 新規浸潤影 → 抗菌薬開始','人工呼吸器関連肺炎（VAP）: 挿管48h以降 → 喀痰培養 + 広域抗菌薬','無気肺は通常軽症で72h以内に自然改善'],
      workup:['胸部X線','SpO2','喀痰培養（肺炎疑い時）','CBC・CRP'],
      disposition:'無気肺→経過観察。肺炎→抗菌薬開始',
      pitfall:'「術後だから熱が出て当然」で済ませない。38.5℃以上が48h以上続く場合は感染を疑う',
    },
  },
  postop_water_wound:{id:'postop_water_wound',title:'術後3-5日: UTI / 創部感染',
    result:{severity:'moderate',title:'UTI / 創部感染（SSI）',
      actions:['尿道カテーテル留置中 → CAUTI疑い: 尿培養提出 + カテーテル抜去/交換検討','創部感染（SSI）: 発赤・腫脹・排膿 → 創部培養 + 抗菌薬 + 必要に応じてドレナージ','腹腔内膿瘍（腹部手術後）: CT造影で評価 → ドレナージ','早期のカテーテル抜去がCAUTI予防の最善策'],
      workup:['尿検査・尿培養','創部の診察','腹部CT（腹腔内膿瘍疑い時）','CBC・CRP','血液培養（菌血症疑い時）'],
      disposition:'軽症→抗菌薬で経過観察。膿瘍→ドレナージ',
      pitfall:'CAUTI診断には症状が必要（発熱・側腹部痛等）。無症候性細菌尿（カテーテル留置中は高頻度）への治療は不要',
    },
  },
  postop_dvt:{id:'postop_dvt',title:'術後5日以降: DVT/PE',
    result:{severity:'urgent',title:'術後DVT/PE疑い',
      actions:['下肢腫脹・疼痛・Homans sign → 下肢静脈エコー','呼吸困難・胸痛・SpO2低下 → CTPA','D-dimer（術後は上昇しやすいため解釈に注意）','DVT確認 → 抗凝固療法開始（出血リスクと天秤）','術後PE予防: 弾性ストッキング + 間欠的空気圧迫 + 早期離床'],
      workup:['下肢静脈エコー','D-dimer（参考程度）','CTPA（PE疑い時）','心電図','心エコー（右心負荷）'],
      disposition:'DVT/PE確認→抗凝固開始 + 入院管理',
      pitfall:'術後のD-dimerは非特異的に上昇するため、臨床的にPEを疑ったらCTPAを直接施行する方が良い場合も',
    },
  },
  drug_fever:{id:'drug_fever',title:'薬剤熱',
    result:{severity:'low',title:'薬剤熱 — 除外診断',
      actions:['薬剤熱の特徴: 比較的元気（relative bradycardia）、好酸球↑、薬剤開始5-10日後','原因薬剤: β-ラクタム系（最多）、抗てんかん薬、アロプリノール、ヘパリン、フェニトイン','診断: 原因薬剤の中止 → 24-72hで解熱すれば確定的','他の感染源を十分に除外した上で疑う（除外診断）','薬剤性の場合、同系統の薬剤で再投与すると再発'],
      workup:['CBC + 分画（好酸球↑）','CRP（薬剤熱では上昇しにくいことも）','肝機能（DILI合併）','血液培養（感染除外）'],
      disposition:'原因薬剤中止で解熱→経過観察',
      pitfall:'「薬剤熱だろう」で他の感染を見逃さない。薬剤熱は除外診断であり、安易に診断しない',
    },
  },
  cvc:{id:'cvc',title:'💉 CVC関連血流感染（CRBSI）疑い',
    result:{severity:'urgent',title:'CRBSI — カテーテル関連血流感染',
      actions:['血液培養: CVC lumenから + 末梢静脈から 同時に2セット採取','DTP（differential time to positivity）: CVC培養が末梢より2h以上早く陽性→CRBSIを示唆','CVC抜去が最も確実な治療（特にS. aureus, Candida, 複雑性感染）','経験的抗菌薬: VCM + グラム陰性桿菌カバー（CFPM or MEPM）','カテーテル先端培養（抜去時）','S. aureus菌血症 → 心エコー（IE除外）+ 4-6週間の抗菌薬'],
      workup:['血液培養（CVC + 末梢 ×2セット）','CBC・CRP・PCT','カテーテル先端培養','心エコー（S. aureus時）'],
      disposition:'入院管理（菌血症が確認されるまで）',
      pitfall:'S. aureus菌血症は合併症率が高い（IE, 骨髄炎, 化膿性関節炎）。「CVC抜いて解熱した」だけで終わりにせず、follow-up血培と心エコーを',
    },
  },
  cauti:{id:'cauti',title:'🚿 CAUTI（カテーテル関連尿路感染）',
    result:{severity:'moderate',title:'CAUTI — カテーテル抜去が第一',
      actions:['尿道カテーテル抜去（可能なら）→ 抜去後に自排尿で尿培養再提出','抗菌薬: 尿培養結果に基づき選択（経験的にはCTRX or LVFX）','カテーテル抜去できない場合: カテーテル交換 + 抗菌薬','治療期間: 7日間（症状改善速やかなら）、14日間（改善遅い場合）','予防: 不要なカテーテルの早期抜去、closed drainage system'],
      workup:['尿検査・尿培養','CBC・CRP','血液培養（菌血症疑い時）'],
      disposition:'抗菌薬開始 + カテーテル管理',
      pitfall:'カテーテル留置中の無症候性細菌尿は治療不要（妊婦と泌尿器手術前を除く）。「尿が濁っている」だけでは治療適応なし',
    },
  },
  cdi:{id:'cdi',title:'💊 C. difficile感染症（CDI）',
    result:{severity:'urgent',title:'CDI — 偽膜性腸炎',
      actions:['便中CD toxin A/B検査 or GDH + toxin 2段階検査','原因抗菌薬の中止（可能なら）','軽症〜中等症: バンコマイシン 125mg 内服 ×4/日 ×10日間（第一選択）','　or フィダキソマイシン 200mg 内服 ×2/日 ×10日間','重症（WBC≧15000, Cr≧1.5, 低アルブミン）: VCM 500mg 内服 ×4/日','劇症型（ショック・イレウス・中毒性巨大結腸）: VCM内服 + メトロニダゾール iv + 外科コンサルト','再発CDI: フィダキソマイシン or VCM漸減投与 or FMT（糞便移植）検討','ロペラミド（止痢薬）は禁忌'],
      workup:['便中CD toxin','CBC（WBC）','Cr・アルブミン','腹部X線 or CT（中毒性巨大結腸除外）','乳酸（重症時）'],
      disposition:'軽症→同一病棟で管理（接触予防策）。重症→ICU検討',
      pitfall:'CDIにメトロニダゾール内服は推奨されなくなった（再発率が高い）。第一選択はVCM内服 or フィダキソマイシン。PPIはCDIリスク因子→不要なPPIは中止',
    },
  },
  general:{id:'general',title:'Step 2: その他の院内発熱',
    result:{severity:'moderate',title:'院内発熱の系統的評価',
      actions:['身体診察: 全身くまなく（皮膚: 褥瘡・蜂窩織炎、腹部: 腹膜刺激、関節: 化膿性関節炎）','全デバイスの確認: CVC刺入部・末梢ルート・ドレーン・尿カテ','肺: 聴診 + 胸部X線（院内肺炎/無気肺）','腹部: 術後膿瘍 → CT','褥瘡感染: 発赤・排膿 → 培養','深部静脈血栓症: 下肢腫脹 → エコー','薬剤熱: 好酸球↑ + relative bradycardia + 薬剤開始後','偽痛風/痛風: 関節痛 + 関節液穿刺 → 結晶確認','Clostridium difficile: 抗菌薬使用歴 + 下痢','副鼻腔炎（経鼻挿管後）: 頭部CT'],
      workup:['血液培養2セット','尿検査・尿培養','胸部X線','CBC・CRP・PCT','喀痰培養','必要に応じてCT（腹腔内膿瘍等）','便CD toxin（下痢あれば）'],
      disposition:'原因に応じた治療と管理',
      pitfall:'院内発熱の10-15%は非感染性（薬剤熱・DVT/PE・偽痛風・副腎不全・輸血後反応）。感染を除外した上で非感染性原因も考慮',
    },
  },
}
const sevColor={critical:{bg:'bg-[#FDECEA]',border:'border-[#D93025]',text:'text-[#B71C1C]',badge:'🚨 緊急'},urgent:{bg:'bg-[#FFF8E1]',border:'border-[#F9A825]',text:'text-[#E65100]',badge:'⚠️ 準緊急'},moderate:{bg:'bg-[#E8F0FE]',border:'border-[#4285F4]',text:'text-[#1565C0]',badge:'ℹ️ 中等度'},low:{bg:'bg-[#E6F4EA]',border:'border-[#34A853]',text:'text-[#1B5E20]',badge:'✅ 低リスク'}}
export default function HospitalFeverPage(){
  const[path,setPath]=useState<string[]>(['start']);const current=tree[path[path.length-1]];const hc=(v:string)=>{if(current?.next){const n=current.next(v);if(tree[n])setPath(p=>[...p,n])}};const gb=()=>{if(path.length>1)setPath(p=>p.slice(0,-1))};const rs=()=>setPath(['start']);if(!current)return null;const sc=current.result?sevColor[current.result.severity]:null
  return(<div className="max-w-3xl mx-auto"><nav className="text-sm text-muted mb-6"><Link href="/" className="hover:text-ac">ホーム</Link><span className="mx-2">›</span><Link href="/tools" className="hover:text-ac">臨床ツール</Link><span className="mx-2">›</span><Link href="/tools/er" className="hover:text-ac">ER対応</Link><span className="mx-2">›</span><span>発熱（院内）</span></nav>
  <header className="mb-6"><span className="inline-block text-sm bg-dnl text-dn px-2.5 py-0.5 rounded-full font-medium mb-2">🏥 院内対応</span><h1 className="text-2xl font-bold text-tx mb-1">発熱（院内）</h1><p className="text-sm text-muted">5D評価 + 術後W³I²F → FN/CRBSI/CAUTI/CDI/薬剤熱の系統的鑑別</p></header>
  <ERDisclaimerBanner /><div className="mb-4 flex items-center gap-2">{path.length>1&&<button onClick={gb} className="text-xs text-ac px-2 py-1 rounded border border-ac/20 hover:bg-acl transition-colors">← 戻る</button>}{path.length>1&&<button onClick={rs} className="text-xs text-muted px-2 py-1 rounded border border-br hover:bg-s1 transition-colors">最初から</button>}</div>
  {current.choices&&!current.result&&(<div className="bg-s0 border border-br rounded-xl p-5 mb-6"><h2 className="text-base font-bold text-tx mb-2">{current.title}</h2>{current.desc&&<p className="text-sm text-muted mb-4">{current.desc}</p>}<div className="space-y-2">{current.choices.map(c=>(<button key={c.value} onClick={()=>hc(c.value)} className={`w-full text-left p-4 rounded-xl border-2 transition-all ${c.danger?'border-[#D93025]/30 hover:border-[#D93025] hover:bg-[#FDECEA]':'border-br hover:border-ac/40 hover:bg-acl'}`}><span className="text-sm font-medium text-tx">{c.icon&&<span className="mr-2">{c.icon}</span>}{c.label}</span></button>))}</div></div>)}
  {current.result&&sc&&(<div className={`${sc.bg} border-2 ${sc.border} rounded-xl p-5 mb-6`}><div className="flex items-center gap-2 mb-3"><span className={`text-xs font-bold px-2.5 py-1 rounded-full ${sc.text} bg-white/70`}>{sc.badge}</span></div><h2 className={`text-lg font-bold mb-3 ${sc.text}`}>{current.result.title}</h2><div className="space-y-4"><div><p className="text-xs font-bold text-tx mb-2">アクション</p><div className="space-y-1.5">{current.result.actions.map((a,i)=><p key={i} className="text-sm text-tx leading-relaxed">{a}</p>)}</div></div><div><p className="text-xs font-bold text-tx mb-2">検査オーダー</p><div className="flex flex-wrap gap-1.5">{current.result.workup.map((w,i)=><span key={i} className="text-xs px-2 py-0.5 rounded bg-white/60 text-tx">{w}</span>)}</div></div><div className="flex items-center gap-2"><p className="text-xs font-bold text-tx">Disposition:</p><p className="text-sm text-tx">{current.result.disposition}</p></div>{current.result.pitfall&&(<div className="bg-white/60 rounded-lg p-3"><p className="text-xs font-bold text-[#E65100] mb-1">⚠️ ピットフォール</p><p className="text-xs text-tx leading-relaxed">{current.result.pitfall}</p></div>)}</div><ERResultCaution /><button onClick={rs} className="mt-4 w-full py-2.5 bg-white/60 rounded-xl text-sm font-medium text-tx hover:bg-white/80 transition-colors">最初からやり直す</button></div>)}
  <ERDisclaimerFooter /></div>)
}
